/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    plans: Plan;
    services: Service;
    projects: Project;
    cases: Case;
    clients: Client;
    testimonials: Testimonial;
    faqs: Faq;
    leads: Lead;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    plans: PlansSelect<false> | PlansSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    landing: Landing;
    'site-settings': SiteSetting;
    seo: Seo;
    privacy: Privacy;
  };
  globalsSelect: {
    landing: LandingSelect<false> | LandingSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Arraste para ordenar: a ordem aqui é a ordem dos cards em cada aba.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  _order?: string | null;
  /**
   * Usado na mensagem do WhatsApp e nos relatórios. No card, o título é montado pela aba: SITE, + MARCA, + INSTA, + NOME.
   */
  name: string;
  /**
   * O card lista todos os serviços avulsos, com check nos incluídos. Com mais de um serviço, mostra o "De" (soma dos avulsos) e a economia.
   */
  services: (number | Service)[];
  /**
   * Vazio = "Sob consulta".
   */
  price?: number | null;
  deadlineDays?: number | null;
  /**
   * Se vazio: "Oi! Vim pelo site e tenho interesse no plano <nome>."
   */
  whatsappMessage?: string | null;
  tabs: ('site' | 'marca')[];
  /**
   * Card com fundo verde e selo.
   */
  highlight?: boolean | null;
  highlightLabel?: string | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Preço de tabela de cada serviço. O "De" e a economia dos combos são calculados a partir daqui.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Título do serviço dentro dos cards de plano. Ex: Site, Marca, Kit Insta, Nome.
   */
  shortName?: string | null;
  /**
   * Ex: 1390.90. Vazio = sob consulta (ex: naming).
   */
  price?: number | null;
  deadlineDays?: number | null;
  /**
   * O que o cliente ganha, em 2 ou 3 palavras por item. Ex: Até 5 páginas.
   */
  includes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Trabalhos da seção Portfólio. Arraste para mudar a ordem. Só publique com autorização do cliente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  /**
   * Nome do cliente ou do projeto.
   */
  title: string;
  /**
   * Uma linha. Ex: Identidade visual e site institucional.
   */
  summary?: string | null;
  /**
   * Quadrada (1:1), de preferência 1200x1200px. Imagem ou vídeo .mp4.
   */
  coverImage: number | Media;
  hoverImage?: (number | null) | Media;
  /**
   * Ex: Bradda, Plathanus.
   */
  partner?: string | null;
  /**
   * Site no ar ou case no Behance.
   */
  url?: string | null;
  /**
   * Site e Marca viram as abas do portfólio. Um projeto pode estar nas duas.
   */
  categories?: ('marca' | 'site' | 'insta')[] | null;
  /**
   * Marque só depois da autorização do cliente.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreve a imagem para leitores de tela e buscadores.
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Casos reais, com autorização do cliente. Sem nenhum publicado, a seção some do site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  _order?: string | null;
  client: string;
  /**
   * Ex: Marca refeita e site novo
   */
  summary?: string | null;
  /**
   * O que o cliente tinha. Mesma proporção do "Depois".
   */
  beforeImage: number | Media;
  /**
   * O projeto do Joycombo.
   */
  afterImage: number | Media;
  beforeLabel?: string | null;
  afterLabel?: string | null;
  /**
   * Marque só depois da autorização do cliente.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Faixa de logos. Só com autorização do cliente.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * SVG ou PNG transparente, de preferência numa cor só. Sem logo, aparece o nome.
   */
  logo?: (number | null) | Media;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Com autorização de uso de nome e foto. Sem nenhum publicado, a seção some.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Ex: CEO da Sollevo
   */
  role?: string | null;
  /**
   * Breve: duas ou três frases.
   */
  text: string;
  /**
   * Quadrada. Sem foto, aparece um avatar pixel gerado a partir do nome.
   */
  photo?: (number | null) | Media;
  published?: boolean | null;
  /**
   * Depoimento de exemplo para testar o layout. Nunca aparece no site publicado, só no ambiente de teste.
   */
  isSample?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Respostas diretas, sem trocadilho. Arraste para ordenar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  _order?: string | null;
  question: string;
  /**
   * Linha em branco separa parágrafos.
   */
  answer: string;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quem preencheu o formulário do site. Os dados seguem a Política de Privacidade.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  whatsapp: string;
  segment?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmContent?: string | null;
  utmTerm?: string | null;
  priceVariant?: string | null;
  gclid?: string | null;
  fbclid?: string | null;
  landingUrl?: string | null;
  status?: ('novo' | 'conversa' | 'fechou' | 'perdido') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  services?: T;
  price?: T;
  deadlineDays?: T;
  whatsappMessage?: T;
  tabs?: T;
  highlight?: T;
  highlightLabel?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  shortName?: T;
  price?: T;
  deadlineDays?: T;
  includes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  summary?: T;
  coverImage?: T;
  hoverImage?: T;
  partner?: T;
  url?: T;
  categories?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  _order?: T;
  client?: T;
  summary?: T;
  beforeImage?: T;
  afterImage?: T;
  beforeLabel?: T;
  afterLabel?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  logo?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  role?: T;
  text?: T;
  photo?: T;
  published?: T;
  isSample?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  whatsapp?: T;
  segment?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmContent?: T;
  utmTerm?: T;
  priceVariant?: T;
  gclid?: T;
  fbclid?: T;
  landingUrl?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Todos os textos da página. Campo vazio volta para o texto padrão.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number;
  /**
   * Não aparece na tela: é o título principal para o Google e leitores de tela. Diz o que é e pra quem.
   */
  heroLine?: string | null;
  heroCtaLabel?: string | null;
  /**
   * Mensagem que já vem escrita quando a pessoa abre o WhatsApp. Vale para o botão do menu e o flutuante.
   */
  heroWhatsMessage?: string | null;
  /**
   * .mp4 (H.264), em loop, sem áudio, 1920x840. O vídeo do Remotion sai em video/out/.
   */
  heroVideo?: (number | null) | Media;
  /**
   * .mp4 1080x1350 (pasta video-mobile/ do projeto). Se vazio, usa o horizontal.
   */
  heroVideoMobile?: (number | null) | Media;
  /**
   * Aparece antes do vídeo carregar. Primeiro quadro do vídeo.
   */
  heroPoster?: (number | null) | Media;
  heroPosterMobile?: (number | null) | Media;
  casesKicker?: string | null;
  casesTitle?: string | null;
  casesIntro?: string | null;
  audienceKicker?: string | null;
  /**
   * Curto: até umas 5 palavras. O resto vai no texto de apoio.
   */
  audienceTitle?: string | null;
  audienceIntro?: string | null;
  audienceCards?:
    | {
        title: string;
        text?: string | null;
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        buttonLabel?: string | null;
        tab?: ('marca' | 'site') | null;
        id?: string | null;
      }[]
    | null;
  portfolioKicker?: string | null;
  portfolioTitle?: string | null;
  portfolioIntro?: string | null;
  portfolioTabAll?: string | null;
  portfolioTabSites?: string | null;
  portfolioTabBrands?: string | null;
  /**
   * Aparece quando a aba escolhida ainda não tem projeto publicado.
   */
  portfolioEmpty?: string | null;
  testimonialsKicker?: string | null;
  testimonialsTitle?: string | null;
  aboutKicker?: string | null;
  aboutName?: string | null;
  aboutRole?: string | null;
  /**
   * Linha em branco separa parágrafos.
   */
  aboutText?: string | null;
  /**
   * Imagem ou .mp4 (toca em loop, sem som). Proporção 4:5.
   */
  aboutPhoto?: (number | null) | Media;
  aboutStats?:
    | {
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  faqKicker?: string | null;
  faqTitle?: string | null;
  plansKicker?: string | null;
  plansTitle?: string | null;
  plansIntro?: string | null;
  /**
   * No teste A/B, cada visitante fica sempre na mesma versão e os eventos de clique levam a versão junto.
   */
  priceDisplay?: ('aberto' | 'a-partir' | 'teste-ab') | null;
  tabPrefix?: string | null;
  tabSiteLabel?: string | null;
  tabMarcaLabel?: string | null;
  planCtaLabel?: string | null;
  fromPrefix?: string | null;
  /**
   * Linha discreta abaixo dos preços.
   */
  paymentNote?: string | null;
  /**
   * Ex: o plano com criação de nome.
   */
  onRequestLabel?: string | null;
  customTitle?: string | null;
  customText?: string | null;
  customCtaLabel?: string | null;
  customMessage?: string | null;
  /**
   * Use {plano} para o que o card anterior já tem (ex: Site + Marca). Evita repetir os mesmos itens nos cards.
   */
  cumulativePrefix?: string | null;
  /**
   * Ex: domínio e hospedagem.
   */
  servicesNote?: string | null;
  /**
   * Texto pequeno no fim da seção.
   */
  outOfScope?: string | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  ctaButtonLabel?: string | null;
  /**
   * Mensagem que já vem escrita quando a pessoa abre o WhatsApp.
   */
  ctaWhatsMessage?: string | null;
  formTitle?: string | null;
  formButtonLabel?: string | null;
  formText?: string | null;
  /**
   * Use {nome} e {segmento}.
   */
  formMessage?: string | null;
  gameEnabled?: boolean | null;
  gamePointsPerHit?: number | null;
  gamePointsGoal?: number | null;
  gameCouponCode?: string | null;
  gameCouponText?: string | null;
  gameCouponCta?: string | null;
  /**
   * Use {codigo} para o cupom.
   */
  gameCouponMessage?: string | null;
  footerTagline?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteTitle?: string | null;
  siteDescription?: string | null;
  ogImage?: (number | null) | Media;
  googleSiteVerification?: string | null;
  /**
   * Ex: 5548999450235. Vale para todos os botões do site.
   */
  whatsapp?: string | null;
  email?: string | null;
  instagram?: string | null;
  /**
   * Aparece no rodapé quando preenchido.
   */
  cnpj?: string | null;
  city?: string | null;
  region?: string | null;
  /**
   * Só números. Eventos: Contact (WhatsApp) e Lead (formulário).
   */
  metaPixelId?: string | null;
  /**
   * Ex: G-XXXXXXXXXX
   */
  ga4Id?: string | null;
  /**
   * Ex: AW-123456789
   */
  googleAdsId?: string | null;
  /**
   * A parte depois da barra em AW-123/abcDEF.
   */
  adsLabelWhatsapp?: string | null;
  adsLabelForm?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Como o site aparece no Google e no preview dos links (WhatsApp, Instagram). Campo vazio volta para o padrão.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Até 60 caracteres. É o texto azul no resultado do Google e o nome da aba do navegador.
   */
  title?: string | null;
  /**
   * Até 155 caracteres. Aparece embaixo do título no Google e no preview do link.
   */
  description?: string | null;
  /**
   * Separadas por vírgula. O Google quase não usa, mas outros buscadores sim.
   */
  keywords?: string | null;
  /**
   * 1200x630px. Aparece quando o link é enviado no WhatsApp, Instagram etc. Vazio = imagem padrão com a marca.
   */
  ogImage?: (number | null) | Media;
  privacyTitle?: string | null;
  privacyDescription?: string | null;
  /**
   * Desmarcado, o site pede para não aparecer em nenhum buscador (útil enquanto não está pronto).
   */
  indexable?: boolean | null;
  /**
   * Caminhos que o Google não deve visitar, além do painel. Ex: /politica-de-privacidade
   */
  blockedPaths?:
    | {
        path: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Só o código do content da meta tag google-site-verification.
   */
  googleVerification?: string | null;
  /**
   * Só o código do content da meta tag msvalidate.01.
   */
  bingVerification?: string | null;
  businessName?: string | null;
  founder?: string | null;
  /**
   * Viram <meta name="..." content="..."> no código da página.
   */
  metaTags?:
    | {
        name: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Página /politica-de-privacidade. Se o texto estiver vazio, o site mostra a política padrão.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: number;
  updatedOn?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  heroLine?: T;
  heroCtaLabel?: T;
  heroWhatsMessage?: T;
  heroVideo?: T;
  heroVideoMobile?: T;
  heroPoster?: T;
  heroPosterMobile?: T;
  casesKicker?: T;
  casesTitle?: T;
  casesIntro?: T;
  audienceKicker?: T;
  audienceTitle?: T;
  audienceIntro?: T;
  audienceCards?:
    | T
    | {
        title?: T;
        text?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        buttonLabel?: T;
        tab?: T;
        id?: T;
      };
  portfolioKicker?: T;
  portfolioTitle?: T;
  portfolioIntro?: T;
  portfolioTabAll?: T;
  portfolioTabSites?: T;
  portfolioTabBrands?: T;
  portfolioEmpty?: T;
  testimonialsKicker?: T;
  testimonialsTitle?: T;
  aboutKicker?: T;
  aboutName?: T;
  aboutRole?: T;
  aboutText?: T;
  aboutPhoto?: T;
  aboutStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  faqKicker?: T;
  faqTitle?: T;
  plansKicker?: T;
  plansTitle?: T;
  plansIntro?: T;
  priceDisplay?: T;
  tabPrefix?: T;
  tabSiteLabel?: T;
  tabMarcaLabel?: T;
  planCtaLabel?: T;
  fromPrefix?: T;
  paymentNote?: T;
  onRequestLabel?: T;
  customTitle?: T;
  customText?: T;
  customCtaLabel?: T;
  customMessage?: T;
  cumulativePrefix?: T;
  servicesNote?: T;
  outOfScope?: T;
  ctaTitle?: T;
  ctaText?: T;
  ctaButtonLabel?: T;
  ctaWhatsMessage?: T;
  formTitle?: T;
  formButtonLabel?: T;
  formText?: T;
  formMessage?: T;
  gameEnabled?: T;
  gamePointsPerHit?: T;
  gamePointsGoal?: T;
  gameCouponCode?: T;
  gameCouponText?: T;
  gameCouponCta?: T;
  gameCouponMessage?: T;
  footerTagline?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  googleSiteVerification?: T;
  whatsapp?: T;
  email?: T;
  instagram?: T;
  cnpj?: T;
  city?: T;
  region?: T;
  metaPixelId?: T;
  ga4Id?: T;
  googleAdsId?: T;
  adsLabelWhatsapp?: T;
  adsLabelForm?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  keywords?: T;
  ogImage?: T;
  privacyTitle?: T;
  privacyDescription?: T;
  indexable?: T;
  blockedPaths?:
    | T
    | {
        path?: T;
        id?: T;
      };
  googleVerification?: T;
  bingVerification?: T;
  businessName?: T;
  founder?: T;
  metaTags?:
    | T
    | {
        name?: T;
        content?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  updatedOn?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}